###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: fiareads-mailhog
      ports:
        - "8081:8025"

    redis:
      image: redis:alpine
      container_name: fiareads-redis

    mariadb:
      image: mariadb:10.1
      container_name: fiareads-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=db
        - MYSQL_USER=db
        - MYSQL_PASSWORD=db
      ports:
        - "8083:3306"

    elasticsearch:
      image: elasticsearch:5.4-alpine
      container_name: fiareads-elasticsearch

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - mariadb:mysql
        ports:
          - 8084:80
        environment:
          PMA_USER: db
          PMA_PASSWORD: db
          PMA_HOST: mariadb

    webserver:
      image: nginx:alpine
      container_name: fiareads-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: fiareads-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

